# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factorial.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x61\x63torial.proto\x12\x05utils\"\"\n\x10\x46\x61\x63torialRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"#\n\x11\x46\x61\x63torialResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2V\n\tFactorial\x12I\n\x12\x43\x61lculateFactorial\x12\x17.utils.FactorialRequest\x1a\x18.utils.FactorialResponse\"\x00\x42\x08Z\x06/utilsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factorial_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006/utils'
  _FACTORIALREQUEST._serialized_start=26
  _FACTORIALREQUEST._serialized_end=60
  _FACTORIALRESPONSE._serialized_start=62
  _FACTORIALRESPONSE._serialized_end=97
  _FACTORIAL._serialized_start=99
  _FACTORIAL._serialized_end=185
# @@protoc_insertion_point(module_scope)
