version: "3.8"
services:
  python_client:
    build: ./Client
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - GO_SERVER_HOST=go_server
      - GO_SERVER_PORT=3000
  go_server:
    build: ./Server/gRPC
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

