# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import utils.utils_pb2 as utils__pb2


class FactorialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateFactorial = channel.unary_unary(
                '/utils.Factorial/CalculateFactorial',
                request_serializer=utils__pb2.FactorialRequest.SerializeToString,
                response_deserializer=utils__pb2.FactorialResponse.FromString,
                )


class FactorialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateFactorial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactorialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateFactorial': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFactorial,
                    request_deserializer=utils__pb2.FactorialRequest.FromString,
                    response_serializer=utils__pb2.FactorialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'utils.Factorial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Factorial(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateFactorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utils.Factorial/CalculateFactorial',
            utils__pb2.FactorialRequest.SerializeToString,
            utils__pb2.FactorialResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
